services:
  mongo:
    image: mongo:6.0
    container_name: tt-mongo
    ports:
      - "27017:27017" # hostPort:containerPort - fixed host port 27017
    environment:
      MONGO_INITDB_DATABASE: time-tracker
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data: